/* ===================== chatbot-strings.js — ChatBot: teksty interfejsu (PL / EN) =====================
   Słowniki STR i t(k): tekst w bieżącym języku (CM.i18n), brakujący klucz → wersja polska → sam klucz.
   Bez DOM; ładowany przed chatbot-core.js, chatbot-render.js i chatbot.js. */
CM.ChatBotStrings = (function(){
  const I=CM.i18n;

  const STR={
  pl:{
    'name':'ChatBot','subtitle':'Asystent CodeMap · Mistral',
    'open':'Otwórz ChatBota','collapse':'Zwiń do paska','newchat':'Nowa rozmowa','history':'Historia rozmów','togglebar':'Pokaż / ukryj historię',
    'placeholder':'Napisz wiadomość lub zleć akcję w aplikacji…','send':'Wyślij','stop':'Zatrzymaj',
    'welcome':'Cześć! Jestem **ChatBot** — wbudowany asystent CodeMap. Znam stan Twojej aplikacji i mogę w niej działać. Poproś np. *„wczytaj demo"*, *„zmień układ na force"*, *„pokaż hotspoty"* albo zadaj dowolne pytanie.',
    'aborted':'(przerwano)','errPrefix':'⚠ ',
    'noKey':'Brak działającego klucza API. Dodaj i przetestuj klucz w Ustawieniach → AI — albo przełącz się tam na **model lokalny** lub **Ollamę** (bez klucza).','goSettings':'Otwórz Ustawienia → AI',
    'noWebGPU':'Wybrany jest **lokalny model AI**, ale ta przeglądarka nie obsługuje WebGPU (wymagany Chrome/Edge 113+). Przełącz provider w Ustawieniach → AI albo zaktualizuj przeglądarkę.',
    'subLocal':'Asystent CodeMap · lokalny','notDownloaded':'nie pobrany','modelSel':'Przełącz lokalny model (pobrane w Ustawieniach → AI)',
    'subOllama':'Asystent CodeMap · Ollama','modelSelOllama':'Przełącz model Ollamy','ollamaOffline':'Ollama offline — uruchom serwer',
    'noModelsDl':'Brak pobranych modeli — pobierz w Ustawieniach → AI','didActions':'Zrobione ⚡',
    'thinking':'Myślę…','thoughts':'Przebieg rozumowania','stLoading':'ładuję model…',
    'copyCode':'Kopiuj kod','runCode':'Uruchom w oknie podglądu','genTime':'Czas utworzenia odpowiedzi / wykonania polecenia','dragHint':'Przeciągnij, aby przenieść (dwuklik = przywróć pozycję)',
    'untitled':'Nowa rozmowa','today':'dziś','empty':'Brak rozmów.','delConfirm':'Usunąć tę rozmowę?',
    'edit':'Edytuj wiadomość','save':'Zapisz i wyślij ponownie','cancel':'Anuluj','regen':'Wygeneruj odpowiedź ponownie','copy':'Kopiuj','copied':'Skopiowano',
    'del':'Usuń rozmowę','done':'✓ wykonano','failed':'nie udało się',
    'helpHead':'Oto, co potrafię w CodeMap. Wpisz **/** w polu wiadomości, aby wybrać narzędzie z listy (Enter uruchamia), albo poproś zwykłym zdaniem, np. „ustaw układ treemap”.',
    'noCommand':'Nie wykonałem żadnej akcji — to nie brzmiało jak polecenie. Wpisz **/**, aby zobaczyć listę narzędzi, albo napisz np. „włącz jasny motyw”.',
    'argMissing':'Brakuje argumentu. Użycie: ','errNetwork':'Brak połączenia z dostawcą AI (sieć lub serwer nie odpowiada). Sprawdź połączenie albo wybierz inny model w Ustawieniach → AI.',
    'errAuth':'Dostawca odrzucił klucz API — przetestuj go w Ustawieniach → AI.','errRate':'Przekroczono limit zapytań u dostawcy — spróbuj za chwilę.',
    'errCtx':'Rozmowa jest za długa dla tego modelu — zacznij nową rozmowę (+) albo wybierz większy model.',
    'errGpu':'Model lokalny nie zmieścił się w pamięci GPU albo sterownik przerwał pracę — wybierz mniejszy model w Ustawieniach → AI.',
    'errDetails':'szczegóły: ','skipped':'pominięto nieprawidłowe akcje: ',
    'tools':'Narzędzia — wpisz / aby filtrować','toolRun':'Enter = uruchom / wstaw','toolNoMatch':'Brak narzędzi pasujących do zapytania',
    'attachHint':'Upuść element mapy tutaj','attachMax':'Maksymalnie 30 elementów w jednej wiadomości.','attachDup':'Ten element już jest dodany.',
    'attachRemove':'Usuń z wiadomości','attached':'Załączone elementy mapy','attachDrop':'Przeciągnij element mapy do tego okna, aby dodać go do wiadomości',
    'rag':'Pytania o kod (RAG)','ragOn':'Tryb „📚 kod": WŁ — odpowiedzi na podstawie fragmentów kodu projektu (tylko modele lokalne; wyszukiwanie słów, a z modelem embeddingów w Ollamie — semantyczne)','ragOff':'Tryb „📚 kod": WYŁ — zwykła rozmowa i sterowanie aplikacją',
    'ragLocalOnly':'Tryb **📚 kod** wysyła do modelu fragmenty Twoich plików, dlatego działa tylko z modelami **lokalnymi** (przeglądarkowy WebLLM albo Ollama). Przełącz model w Ustawieniach → AI albo wyłącz 📚 w nagłówku czatu.',
    'ragSearching':'Szukam w kodzie…','ragFoundHybrid':'znaleziono fragmenty (semantycznie + słowa)','ragFoundLex':'znaleziono fragmenty (wyszukiwanie słów)',
    'agentNoAnswer':'Model nie sformułował odpowiedzi — fragmenty kodu, które znalazł, są poniżej. Spróbuj zapytać prościej albo wybierz większy model.',
    'ragNothing':'Nie znalazłem w kodzie projektu fragmentów pasujących do pytania. Upewnij się, że projekt został wczytany z treścią plików (folder albo repozytorium), i spróbuj użyć nazw plików, funkcji lub pojęć z kodu.',
    'ragSources':'Źródła','ragGone':'Tego pliku nie ma już na mapie.','agentSteps':'Kroki agenta',
    'doctorAsk':'🩺 Doktor hotspotów: ','doctorPrep':'Zbieram kartotekę pliku…','doctorNoFile':'Nie znalazłem pliku z treścią do zbadania — wczytaj projekt z plikami (folder albo repozytorium) i wskaż plik z kodem.',
    'doctorLocalOnly':'**🩺 Doktor hotspotów** wysyła do modelu fragmenty kodu pliku, dlatego działa tylko z modelami **lokalnymi** (przeglądarkowy WebLLM albo Ollama). Przełącz model w Ustawieniach → AI.',
    'prAsk':'🔍 Przegląd PR #','prPrep':'Składam mapę wpływu i fragmenty zmian…','prNone':'Brak zmienionych plików z treścią — przeanalizuj PR (Projekt → Przegląd PR).',
    'prLocalOnly':'**🔍 Asystent przeglądu PR** wysyła do modelu fragmenty zmian (kod), dlatego działa tylko z modelami **lokalnymi** (przeglądarkowy WebLLM albo Ollama). Przełącz model w Ustawieniach → AI.',
    'quick':'Szybka odpowiedź (bez rozumowania)','quickOn':'Szybka odpowiedź: WŁ — model odpowiada od razu, bez rozumowania','quickOff':'Szybka odpowiedź: WYŁ — model pokazuje tok rozumowania',
    'resize':'Rozciągnij okno','sbResize':'Przeciągnij, aby zmienić szerokość listy rozmów (do 0 = zwiń)',
    'toolArgHint':'Dopisz argument i wciśnij Enter, np. /setLayout treemap',
    'thumbUp':'Pomocna odpowiedź','thumbDown':'Niepomocna odpowiedź',
    'clickToRun':'Akcja zmieniająca stan — kliknij, aby wykonać',
    'histTrimmed':'Pamięć prawie pełna — starsze wiadomości nie są już zapisywane.',
    'histNoSave':'Nie można zapisać historii rozmów (pamięć pełna).',
  },
  en:{
    'name':'ChatBot','subtitle':'CodeMap assistant · Mistral',
    'open':'Open ChatBot','collapse':'Collapse to bar','newchat':'New chat','history':'Conversations','togglebar':'Show / hide history',
    'placeholder':'Write a message or command an action in the app…','send':'Send','stop':'Stop',
    'welcome':"Hi! I'm **ChatBot** — the built-in CodeMap assistant. I know your app's state and can act in it. Try *“load demo”*, *“switch layout to force”*, *“show hotspots”*, or ask me anything.",
    'aborted':'(stopped)','errPrefix':'⚠ ',
    'noKey':'No working API key. Add and test a key in Settings → AI — or switch to the **local model** or **Ollama** there (no key needed).','goSettings':'Open Settings → AI',
    'noWebGPU':'The **local AI model** is selected, but this browser has no WebGPU (Chrome/Edge 113+ required). Switch the provider in Settings → AI or update your browser.',
    'subLocal':'CodeMap assistant · local','notDownloaded':'not downloaded','modelSel':'Switch local model (download in Settings → AI)',
    'subOllama':'CodeMap assistant · Ollama','modelSelOllama':'Switch the Ollama model','ollamaOffline':'Ollama offline — start the server',
    'noModelsDl':'No downloaded models — download in Settings → AI','didActions':'Done ⚡',
    'thinking':'Thinking…','thoughts':'Reasoning trace','stLoading':'loading the model…',
    'copyCode':'Copy code','runCode':'Run in the preview window','genTime':'Answer / command execution time','dragHint':'Drag to move (double-click = reset position)',
    'untitled':'New chat','today':'today','empty':'No conversations.','delConfirm':'Delete this conversation?',
    'edit':'Edit message','save':'Save & resend','cancel':'Cancel','regen':'Regenerate answer','copy':'Copy','copied':'Copied',
    'del':'Delete conversation','done':'✓ done','failed':'failed',
    'helpHead':'Here is what I can do in CodeMap. Type **/** in the message box to pick a tool from the list (Enter runs it), or just ask in plain words, e.g. “set the treemap layout”.',
    'noCommand':'I did not run any action — that did not sound like a command. Type **/** to see the tool list, or write e.g. “switch to the light theme”.',
    'argMissing':'Missing argument. Usage: ','errNetwork':'Cannot reach the AI provider (network or server not responding). Check the connection or pick another model in Settings → AI.',
    'errAuth':'The provider rejected the API key — test it in Settings → AI.','errRate':'The provider rate limit was exceeded — try again in a moment.',
    'errCtx':'This conversation is too long for the model — start a new one (+) or pick a larger model.',
    'errGpu':'The local model did not fit into GPU memory or the driver stopped it — pick a smaller model in Settings → AI.',
    'errDetails':'details: ','skipped':'skipped invalid actions: ',
    'tools':'Tools — type / to filter','toolRun':'Enter = run / insert','toolNoMatch':'No tools match the query',
    'attachHint':'Drop a map element here','attachMax':'At most 30 elements per message.','attachDup':'This element is already attached.',
    'attachRemove':'Remove from message','attached':'Attached map elements','attachDrop':'Drag a map element into this window to attach it to the message',
    'rag':'Code questions (RAG)','ragOn':'"📚 code" mode: ON — answers based on code snippets from the project (local models only; keyword search, semantic with an Ollama embedding model)','ragOff':'"📚 code" mode: OFF — regular chat and app control',
    'ragLocalOnly':'**📚 code** mode sends snippets of your files to the model, so it only works with **local** models (in-browser WebLLM or Ollama). Switch the model in Settings → AI or turn 📚 off in the chat header.',
    'ragSearching':'Searching the code…','ragFoundHybrid':'snippets found (semantic + keywords)','ragFoundLex':'snippets found (keyword search)',
    'agentNoAnswer':'The model did not produce an answer — the code snippets it found are below. Try a simpler question or a larger model.',
    'ragNothing':'I found no code snippets in the project matching the question. Make sure the project was loaded with file contents (a folder or a repository) and try names of files, functions or terms from the code.',
    'ragSources':'Sources','ragGone':'This file is no longer on the map.','agentSteps':'Agent steps',
    'doctorAsk':'🩺 Hotspot doctor: ','doctorPrep':'Gathering the file record…','doctorNoFile':'No file with content to examine — load a project with its files (a folder or a repository) and point to a code file.',
    'doctorLocalOnly':'**🩺 Hotspot doctor** sends code excerpts of the file to the model, so it only works with **local** models (in-browser WebLLM or Ollama). Switch the model in Settings → AI.',
    'prAsk':'🔍 PR review #','prPrep':'Assembling the impact map and change fragments…','prNone':'No changed files with content — analyze the PR first (Project → PR review).',
    'prLocalOnly':'**🔍 PR review assistant** sends change fragments (code) to the model, so it only works with **local** models (in-browser WebLLM or Ollama). Switch the model in Settings → AI.',
    'quick':'Quick answer (no reasoning)','quickOn':'Quick answer: ON — the model answers right away, without reasoning','quickOff':'Quick answer: OFF — the model shows its reasoning',
    'resize':'Resize the window','sbResize':'Drag to resize the conversation list (0 = collapse)',
    'toolArgHint':'Add an argument and press Enter, e.g. /setLayout treemap',
    'thumbUp':'Helpful answer','thumbDown':'Unhelpful answer',
    'clickToRun':'State-changing action — click to run',
    'histTrimmed':'Storage nearly full — older messages are no longer saved.',
    'histNoSave':'Could not save conversation history (storage full).',
  }};
  function t(k){ const l=I.getLang(); const d=STR[l]||STR.pl; return (d&&k in d)?d[k]:(STR.pl[k]||k); }

  return { STR, t };
})();
