/* ===================== settings-strings.js — teksty okna Ustawień i samouczka (PL / EN) ===================== */
// Czyste dane (bez DOM). Czyta je t() z settings.js; moduły zakładek dostają t przez CM.Settings.kit.
// Oba słowniki mają ten sam zestaw kluczy (pilnuje test/settings.test.mjs).
CM.SettingsStrings={
  pl:{
    'title':'Ustawienia',
    'tab.account':'Konto','acct.head':'Konto i synchronizacja','acct.desc':'Rejestracja, logowanie i synchronizacja danych (mapy, migawki, ustawienia, Sejf) między urządzeniami.',
    'tab.lang':'Język','tab.appearance':'Wygląd','tab.ai':'AI','tab.install':'Instalacja',
    'tab.shortcuts':'Skróty',
    'tab.tutorial':'Samouczek','tab.spec':'Specyfikacja','tab.manual':'Instrukcja obsługi','tab.about':'O aplikacji',
    'sc.head':'Skróty klawiszowe i myszy','sc.desc':'Pełna lista skrótów. Klawisze pokazane są jako klawisze; działanie zależy od trybu (CodeMap / MindMap).',
    'sc.grp.nav':'Nawigacja CodeMap','sc.grp.general':'Ogólne','sc.grp.mind':'MindMap',
    'sc.move':'Ruch kamery','sc.zoomIn':'Przybliż','sc.zoomOut':'Oddal',
    'sc.fps':'Tryb nawigacji (rozglądanie się, FPS)','sc.fpsHint':'Włącz klawiszem G lub przyciskiem celownika; mysz = obrót i pochylenie; Esc lub G = wyjście.',
    'sc.arrows':'Przesuwanie widoku','sc.fit':'Dopasuj do ekranu','sc.rotate':'Obrót w lewo / prawo',
    'sc.resetRot':'Reset obrotu','sc.toggle3d':'Przełącz 3D / perspektywę','sc.isolate':'Skup na zaznaczonym',
    'sc.impact':'Widok wpływu zależności','sc.search':'Szukaj','sc.escape':'Odznacz / zamknij','sc.del':'Usuń węzeł','sc.undo':'Cofnij / ponów','sc.edit':'Edytuj węzeł',
    'sc.altS':'Otwórz / zamknij tę ściągawkę skrótów',
    'sc.nodeNav':'Następny węzeł w tym kierunku','sc.nodeNavHint':'zaznaczenie ogłaszane czytnikowi ekranu',
    'sc.nodeOpen':'Rozwiń / zwiń folder, pokaż plik','sc.nodeParent':'Folder nadrzędny / pierwsze dziecko',
    'sc.mouse':'mysz','sc.dblclick':'dwuklik',
    'ai.head':'Asystent AI (Mistral)','ai.desc':'Opcjonalnie. Po podaniu własnego klucza Mistral API aplikacja może przeanalizować STRUKTURĘ projektu (foldery, liczby i rozmiary plików, języki) i zaproponować logiczny podział na moduły/warstwy oraz wskazać „zapachy" struktury.',
    'ai.key':'Klucz Mistral API (przechowywany lokalnie)','ai.model':'Model',
    'ai.keys':'Klucze API (chmura: Mistral, OpenAI, Anthropic Claude, Google Gemini, Groq, OpenRouter, DeepSeek, xAI, Together)',
    'ai.keysHint':'Wklej klucz — dostawca zostanie rozpoznany po formacie klucza i potwierdzony testem (pobranie listy modeli). Klucze zostają w tej przeglądarce i trafiają wyłącznie do API danego dostawcy. Aplikacja używa działających kluczy rotacyjnie, a przy limicie lub błędzie przełącza się na następny.',
    'ai.keyAdd':'Dodaj klucz','ai.keyTest':'Testuj','ai.keySave':'Zapisz','ai.keyDelete':'Usuń klucz','ai.keyDeleteConfirm':'Usunąć ten klucz?',
    'ai.keySaved':'Klucz zapisany.','ai.keyDeleted':'Klucz usunięty.','ai.keyEmpty':'Wklej klucz.','ai.keyExists':'Ten klucz już jest na liście.',
    'ai.keyTesting':'Sprawdzam klucz…','ai.keyOk':'działa','ai.keyModels':'modeli: ','ai.keyUnknownProv':'dostawca nierozpoznany po formacie — kliknij Testuj',
    'ai.keyDetected':'(wykryty po formacie klucza — kliknij Testuj, aby potwierdzić)','ai.keyModel':'Model','ai.keyNone':'Brak kluczy. Dodaj pierwszy poniżej — albo wybierz wyżej model lokalny lub Ollamę (bez klucza).',
    'ai.keyPh':'Klucz API…','ai.keyShow':'Pokaż / ukryj klucz','ai.keysCount':'Działające klucze: ',
    'ai.votes':'Oceny odpowiedzi ChatBota','ai.votesHint':'Suma łapek ze wszystkich rozmów — nie zeruje się.','ai.votesUp':'pomocne','ai.votesDown':'niepomocne',
    'ai.provider':'Dostawca AI','ai.providerHint':'„Model lokalny" = prawdziwy, darmowy LLM działający w 100% na Twoim urządzeniu (WebGPU). Bez klucza, bez wysyłania danych — wagi pobierane są raz i trzymane w pamięci przeglądarki.',
    'ai.provMistral':'Klucze API — chmura (Mistral, OpenAI, Claude, Gemini, Groq…)','ai.provLocal':'Model lokalny (w przeglądarce, za darmo)',
    'ai.provOllama':'Ollama (natywny lokalny serwer — błyskawiczny)',
    'ai.ollamaDesc':'Najszybsza lokalna opcja: modele uruchamia zainstalowana Ollama (ollama.com) — pełna moc komputera, zero obciążania przeglądarki i karty graficznej zakładki. Wymaga działającej aplikacji Ollama.',
    'ai.ollamaCheck':'Sprawdź / odśwież modele','ai.ollamaModel':'Model Ollamy','ai.ollamaOnline':'✓ Ollama online — modele: ',
    'ai.localModel':'Lokalny model','ai.localDl':'Pobierz i uruchom','ai.localDlHint':'Pierwsze uruchomienie pobiera wagi modelu (rozmiar przy nazwie). Kolejne starty są szybkie (cache przeglądarki). Na zintegrowanych GPU (Intel/AMD) polecamy 0.5B–1B; większe modele wymagają dedykowanej karty graficznej.',
    'ai.localReady':'✓ Model gotowy — cała aplikacja (ChatBot, analiza, pytania o elementy) działa lokalnie.',
    'ai.localLoading':'Pobieram / uruchamiam…','ai.localNoGPU':'Ta przeglądarka nie obsługuje WebGPU (wymagany Chrome/Edge 113+). Lokalne modele są niedostępne — użyj Mistral API.',
    'ai.localUnload':'Zwolnij z pamięci (RAM/VRAM)','ai.localDelete':'Usuń pobrane wagi z dysku','ai.localDeleted':'Usunięto pobrane modele: ','ai.localCached':'Pobrane dane modeli w przeglądarce: ',
    'ai.localCancel':'Anuluj pobieranie / ładowanie',
    'ai.localAll':'Wszystkie modele silnika WebLLM','ai.localAllHint':'Pełna lista modeli czatu wbudowana w używaną wersję WebLLM (VRAM w MB). Wybór dopisuje model do listy powyżej.','ai.localAllShow':'Pokaż wszystkie modele','ai.localAllPick':'— wybierz model —',
    'ai.rag':'Indeks kodu (RAG) — tryb „📚 kod" w ChatBocie','ai.ragDesc':'ChatBot w trybie 📚 odpowiada na podstawie fragmentów kodu wczytanego projektu. Wyszukiwanie słów działa zawsze; model embeddingów w Ollamie (np. bge-m3 — dobry po polsku, albo nomic-embed-text) albo 🌐 w przeglądarce (WebLLM, wymaga WebGPU; pobiera się raz) dodaje wyszukiwanie semantyczne. Wektory liczone są na Twoim komputerze i zapisują się w przeglądarce — przy kolejnym wczytaniu liczone są tylko zmienione fragmenty.',
    'ai.ragModel':'Model embeddingów','ai.ragNoModel':'Brak modelu embeddingów — pobierz w Ollamie bge-m3 albo nomic-embed-text, albo użyj przeglądarki z WebGPU (modele 🌐 WebLLM).','ai.ragWeb':'w przeglądarce (WebLLM, najlepszy po angielsku)','ai.ragBuild':'Zbuduj / odśwież indeks semantyczny','ai.ragCancel':'Anuluj','ai.ragClear':'Usuń wektory',
    'ai.ragAgent':'Agent z narzędziami: w trybie 📚 model w Ollamie sam przeszukuje kod, czyta pliki i sprawdza zależności przed odpowiedzią (tylko odczyt; modele bez narzędzi odpowiadają jak zwykle)',
    'ai.ragStat':'Fragmenty: {c} z {f} plików · indeks semantyczny: {v}','ai.ragNoProject':'Wczytaj projekt z treścią plików, aby zbudować indeks.','ai.ragYes':'gotowy ({m}, {d} wym.)','ai.ragNo':'brak (tylko wyszukiwanie słów)','ai.ragDone':'Indeks semantyczny gotowy: ',
    'ai.ollamaPull':'Pobierz model do Ollamy','ai.ollamaPullHint':'Nazwa jak w bibliotece ollama.com (np. qwen2.5:3b). Pobieranie odbywa się w Ollamie, postęp poniżej.','ai.ollamaPullBtn':'Pobierz','ai.ollamaPullDone':'Pobrano: ','ai.ollamaPullCancel':'Anuluj','ai.ollamaSuggest':'Propozycje: ',
    'ai.localList':'Pobrane modele (zarządzanie)','ai.localNone':'Nie pobrano jeszcze żadnego modelu.','ai.localRun':'Uruchom (pobrany — bez ponownego pobierania)',
    'ai.localLoaded':'załadowany','ai.localDelOne':'Usuń','ai.localDelConfirm':'Usunąć pobrane wagi modelu „{n}” z dysku przeglądarki?',
    'ai.privacy':'Prywatność: wysyłana jest TYLKO struktura (ścieżki, liczby, rozmiary, języki) — nigdy treść plików. Klucz trzymany jest wyłącznie w Twojej przeglądarce.',
    'ai.analyze':'Przeanalizuj bieżącą strukturę','ai.working':'Analizuję strukturę…','ai.noProject':'Najpierw wczytaj projekt (CodeMap).','ai.empty':'Brak odpowiedzi.',
    'ai.autotune':'Automatycznie dostrajaj widok przez AI przy wczytywaniu','ai.autotuneHint':'Po wczytaniu projektu AI dobierze które Elementy i Połączenia pokazać oraz parametry Figur (rozmiar węzłów, odstępy, rozmiar napisów), aby mapa pasowała do skali projektu. Wymaga klucza powyżej; wysyła tylko strukturę.',
    'ai.askHead':'Zapytaj o projekt','ai.askPlaceholder':'Zapytaj o projekt… np. gdzie jest logika logowania?','ai.ask':'Zapytaj AI','ai.asking':'Pytam AI…','ai.askEmpty':'Najpierw wpisz pytanie.',
    'ai.layout':'✨ Ułóż mapę przez AI','ai.layoutHint':'AI samodzielnie rozmieszcza moduły — za każdym razem inaczej, bez gotowych układów.','ai.layoutWorking':'AI układa mapę…','ai.layoutDone':'AI ułożyła mapę.',
    'lang.head':'Język interfejsu','lang.desc':'Wybierz język aplikacji. Cały interfejs zostanie natychmiast przetłumaczony, a wybór zapamiętany.',
    'lang.pl':'Polski','lang.en':'English (angielski)',
    'app.head':'Strojenie wyglądu','app.desc':'Pełne suwaki przezroczystości, rozmycia, kolorów i rozmiarów znajdziesz w panelu „Warstwy i filtry" po lewej. Tutaj masz szybkie skróty.',
    'app.theme':'Motyw','app.theme.dark':'Ciemny','app.theme.light':'Jasny',
    'app.accent':'Kolor akcentu','app.open':'Otwórz panel wyglądu','app.reset':'Przywróć domyślny wygląd',
    'app.reset.done':'Przywrócono domyślny wygląd aplikacji.',
    'install.head':'Instalacja i dane','install.desc':'CodeMap to aplikacja PWA — możesz ją zainstalować na pulpicie i używać offline. Twoje mapy i ustawienia są zapisywane lokalnie w przeglądarce.',
    'install.install':'Zainstaluj aplikację','install.install.hint':'Dodaj CodeMap jako samodzielną aplikację (offline).',
    'install.unavailable':'Instalacja niedostępna — aplikacja jest już zainstalowana lub przeglądarka nie udostępniła monitu. Można też użyć opcji „Zainstaluj" w pasku adresu.',
    'install.update':'Sprawdź aktualizacje / przeładuj','install.update.hint':'Pobiera najnowszą wersję i odświeża aplikację.',
    'install.uninstall':'Wyczyść pamięć podręczną (offline)','install.uninstall.hint':'Usuwa service workera i pamięć podręczną. Mapy i ustawienia pozostają.',
    'install.uninstall.done':'Wyczyszczono pamięć podręczną offline. Odśwież stronę.',
    'install.acache':'Wyczyść pamięć analizy','install.acache.hint':'Wyniki analizy plików zapamiętane w przeglądarce (OPFS) — ponowne wczytanie projektu pomija niezmienione pliki. Tylko metryki, importy i nazwy symboli.','install.acache.stat':'Teraz: {n} proj., {mb} MB.','install.acache.done':'Wyczyszczono pamięć analizy.',
    'install.wipe':'Usuń wszystkie dane','install.wipe.hint':'Trwale usuwa migawki, zapisane mapy, mapy myśli, ustawienia i język. Nieodwracalne.',
    'install.wipe.confirm':'Na pewno usunąć WSZYSTKIE dane (migawki, mapy, ustawienia)? Tej operacji nie można cofnąć.',
    'install.wipe.done':'Usunięto wszystkie dane aplikacji.',
    'tut.head':'Interaktywny samouczek','tut.desc':'Animowany przewodnik podświetli po kolei każde narzędzie i przycisk, wyjaśniając do czego służy. Możesz go przerwać w dowolnej chwili klawiszem Esc.',
    'tut.start':'Rozpocznij samouczek','tut.covers':'Samouczek pokazuje: logo, przełącznik trybów, menu Wczytaj, wybór układu, wyszukiwarkę, menu Projekt, ustawienia, panele boczne, filtry, wygląd, narzędzia widoku, tryb 3D kółkiem myszy, kompas (czerwona wskazówka), mapę okolicy/teleportację, przypinanie kompasu, minimapę, panel szczegółów i pasek statusu.',
    'tut.startCode':'Samouczek CodeMap','tut.startMind':'Samouczek MindMap',
    'tut.coversMind':'Samouczek MindMap pokazuje: przełącznik trybów, górny pasek (nazwa + zoom), planszę (dwuklik = nowy węzeł), pasek narzędzi (cofnij/ponów, łączenie, auto-układ, schematy i szablony, dopasowanie), zapis i wczytywanie, eksport, Markdown, panel właściwości oraz oś czasu migawek.',
    'tut.shortcutsTitle':'Skróty klawiszowe',
    'tut.shortcuts':'<b>Ctrl + K</b> (na Windows także <b>Ctrl + ⊞ Win + K</b>) — <b>paleta poleceń</b> (szybkie wyszukanie i uruchomienie dowolnej funkcji) · <b>Ctrl + V</b> — wklej kod · <b>F</b> — dopasuj widok · <b>Q / E</b> — obrót · <b>+ / −</b> — zoom · <b>I</b> — izoluj zaznaczony · <b>Ctrl + Z / Ctrl + Y</b> — cofnij / ponów (MindMap) · <b>Esc</b> — zamknij / wyczyść.',
    'tut.next':'Dalej','tut.prev':'Wstecz','tut.skip':'Pomiń','tut.done':'Zakończ','tut.step':'Krok',
    'about.head':'O aplikacji','about.version':'Wersja','about.author':'Autor','about.tech':'Technologia',
    'about.tech.val':'Czysty JavaScript (bez frameworków i bez kroku budowania), render na HTML5 Canvas, PWA z service workerem. Działa w pełni lokalnie i offline.',
    'about.privacy':'Prywatność','about.privacy.val':'Wszystkie dane pozostają w Twojej przeglądarce. Pliki nie są wysyłane na żaden serwer (poza pobieraniem z GitHub/GitLab/Bitbucket, gdy sam o to poprosisz).',
    'about.repo':'Profil autora na GitHub',
    // ---- tour steps ----
    'tour.brand.t':'Logo CodeMap','tour.brand.b':'Kliknij logo, aby je obrócić (zabawny akcent, dostępny co 10 sekund). To także znak rozpoznawczy aplikacji.',
    'tour.mode.t':'Przełącznik trybów','tour.mode.b':'Przełączaj między <b>CodeMap</b> (mapa kodu i zależności) a <b>MindMap</b> (mapy myśli i schematy). Tryb możesz zmienić w każdej chwili.',
    'tour.load.t':'Menu Wczytaj','tour.load.b':'Wczytaj projekt: <b>folder z urządzenia</b>, <b>pojedyncze pliki</b> lub <b>repozytorium GitHub/GitLab/Bitbucket</b>. Możesz też przeciągnąć pliki na planszę albo wkleić je Ctrl+V.',
    'tour.layout.t':'Wybór układu','tour.layout.b':'Zmień sposób rozmieszczenia węzłów — układy strukturalne (czytelne drzewa, upakowane koła), siłowe (graf zależności) oraz kosmiczne (mgławica, galaktyki).',
    'tour.search.t':'Wyszukiwarka','tour.search.b':'Szukaj plików i ścieżek. Trafienia są podświetlane na mapie; wybierz wynik, aby do niego doskoczyć.',
    'tour.project.t':'Menu Projekt','tour.project.b':'Operacje na całym projekcie: zapis <b>migawek</b> i ich historia, eksport mapy do <b>.json</b> lub <b>obrazu (PNG/SVG)</b>, wykrywanie <b>cykli zależności</b>, <b>hotspoty</b> i porównywanie schematów.',
    'tour.settings.t':'Ustawienia','tour.settings.b':'Ta zębatka otwiera ustawienia — język, instalację, ten samouczek oraz pełną specyfikację i instrukcję obsługi.',
    'tour.leftrail.t':'Panel boczny','tour.leftrail.b':'Tym uchwytem zwijasz i rozwijasz lewy panel z warstwami i filtrami. Analogiczny uchwyt po prawej steruje panelem szczegółów.',
    'tour.elements.t':'Elementy i filtry','tour.elements.b':'Włączaj i wyłączaj widoczność folderów, plików oraz zależności zewnętrznych — i rodzajów połączeń między nimi.',
    'tour.filetypes.t':'Typy plików','tour.filetypes.b':'Każdy język/typ pliku ma swój kolor. Możesz ukrywać wybrane typy, aby skupić mapę na tym, co istotne.',
    'tour.complexity.t':'Filtr złożoności','tour.complexity.b':'Pokazuj tylko pliki powyżej progu wybranej metryki (liczba wierszy, złożoność, liczba funkcji, znaczniki TODO, rozmiar). Świetne do znajdowania „ciężkich" plików.',
    'tour.appearance.t':'Wygląd','tour.appearance.b':'Dostrój przezroczystość okien, rozmycie szkła, kolor akcentu, motyw oraz tło. Aplikacja jest w pełni personalizowalna.',
    'tour.map.t':'Opcje mapy','tour.map.b':'Włączaj animacje, cząsteczki przepływu, siatkę tła, wygięte połączenia i podgląd kodu po najechaniu. Tu też zablokujesz figury.',
    'tour.figures.t':'Figury','tour.figures.b':'Reguluj rozmiar węzłów, odległość między nimi i wielkość napisów, aby mapa była czytelna dla małych i ogromnych projektów.',
    'tour.viewcontrols.t':'Narzędzia widoku','tour.viewcontrols.b':'Przybliżanie, oddalanie, dopasowanie do ekranu, obrót w lewo/prawo i przełącznik pseudo-3D. Pasek można zwinąć.',
    'tour.threed.t':'Tryb 3D kółkiem myszy','tour.threed.b':'Wciśnij <b>kółko myszy</b> i przesuwaj w <b>górę / dół</b>, aby płynnie i dynamicznie przechodzić w tryb <b>3D</b> (pochylenie perspektywy) i z powrotem. To samo robi przycisk sześcianu na pasku narzędzi — właśnie go podejrzewasz. (Obrót w 3D: środkowy lub prawy przycisk myszy.)',
    'tour.compass.t':'Kompas — czerwona wskazówka','tour.compass.b':'Przeciągnij <b>tarczę</b>, aby obrócić kamerę; na tarczy widzisz <b>licznik kątów</b> (np. 0°). <b>Czerwona wskazówka</b> zawsze pokazuje <b>centrum głównej struktury</b> na mapie — dzięki temu wiesz, w którą stronę „wrócić do projektu", nawet po oddaleniu.',
    'tour.compasshood.t':'Mapa okolicy (radar)','tour.compasshood.b':'<b>Dwukrotne kliknięcie</b> kompasu otwiera ten <b>radar całej okolicy</b> — miniaturę wszystkich widocznych węzłów. Kółkiem przybliżasz, a <b>dwuklik elementu = teleportacja</b> wprost do niego na mapie (jest też przycisk „Teleportuj do…"). Świetne do skoku w odległą część dużego projektu.',
    'tour.compasspin.t':'Odpinanie i przypinanie kompasu','tour.compasspin.b':'Małym przyciskiem <b>pinezki</b> (lewy-górny) <b>odepniesz</b> kompas, złapiesz go za <b>uchwyt</b> (górny) i przeniesiesz w <b>dowolne miejsce ekranu</b>, a tą samą pinezką <b>przypniesz</b> go tam ponownie. Drugi przycisk pozwala też zwinąć kompas.',
    'tour.minimap.t':'Minimapa','tour.minimap.b':'Podgląd całej mapy z zaznaczonym widokiem. Pomaga w nawigacji po dużych projektach; można ją zwinąć.',
    'tour.details.t':'Panel szczegółów','tour.details.b':'Po kliknięciu elementu zobaczysz tu metryki, skład wierszy, znaczniki, importy, symbole (funkcje/klasy) i podświetlony podgląd kodu.',
    'tour.status.t':'Pasek statusu','tour.status.b':'Nazwa projektu, liczba węzłów i połączeń, aktualny element pod kursorem, poziom przybliżenia oraz zegar.',
    // ---- MindMap tour steps ----
    'tourmm.mode.t':'Tryb MindMap','tourmm.mode.b':'Jesteś w trybie <b>MindMap</b> — edytorze map myśli i diagramów. Tym przełącznikiem wrócisz do <b>CodeMap</b> w każdej chwili.',
    'tourmm.topbar.t':'Górny pasek','tourmm.topbar.b':'Tu nadasz <b>nazwę</b> mapie myśli i wyregulujesz <b>powiększenie</b> (przyciskami +/− lub kółkiem myszy).',
    'tourmm.canvas.t':'Plansza','tourmm.canvas.b':'<b>Dwuklik</b> w puste miejsce tworzy nowy węzeł, <b>dwuklik węzła</b> go edytuje, a przeciąganie przesuwa widok. Wokół zaznaczonego węzła pojawia się <b>menu</b> z szybkimi akcjami (dziecko, kolor, kształt).',
    'tourmm.tools.t':'Pasek narzędzi','tourmm.tools.b':'Wszystkie narzędzia mapy myśli w jednym miejscu — w kolejnych krokach omówimy najważniejsze.',
    'tourmm.undo.t':'Cofnij / ponów','tourmm.undo.b':'Cofaj i ponawiaj zmiany (także skrótami <b>Ctrl+Z</b> / <b>Ctrl+Y</b>).',
    'tourmm.connect.t':'Łączenie węzłów','tourmm.connect.b':'Włącz <b>tryb łączenia</b> i kliknij dwa węzły, aby je połączyć krawędzią.',
    'tourmm.arrange.t':'Auto-układ','tourmm.arrange.b':'Automatycznie rozmieszcza węzły (radialnie) — szybkie uporządkowanie mapy.',
    'tourmm.layout.t':'Schematy i szablony','tourmm.layout.b':'Wybierz <b>schemat układu</b>, styl linii oraz jeden z <b>22 typów diagramów</b> i 34 szablonów (oś czasu, flowchart, SWOT, kanban, blok kodu i in.).',
    'tourmm.fit.t':'Dopasuj widok','tourmm.fit.b':'Dopasowuje powiększenie tak, aby cała mapa zmieściła się na ekranie.',
    'tourmm.save.t':'Zapis i wczytywanie','tourmm.save.b':'Zapisuj mapy w pamięci urządzenia i wczytuj je później. Obok znajdziesz <b>eksport</b> do pliku, obrazu (PNG/SVG) oraz import.',
    'tourmm.markdown.t':'Markdown','tourmm.markdown.b':'Importuj i eksportuj mapę jako <b>konspekt Markdown</b> — wygodna wymiana z notatkami.',
    'tourmm.inspector.t':'Panel właściwości','tourmm.inspector.b':'Po zaznaczeniu węzła dostroisz tu jego <b>tekst, kolor, kształt, czcionkę</b> i powiązania. Uchwytem obok zwiniesz panel.',
    'tourmm.timeline.t':'Oś czasu migawek','tourmm.timeline.b':'Zapisane migawki układają się w <b>oś czasu</b> z animowanym porównaniem zmian (dodane / zmienione / usunięte węzły).',
  },
  en:{
    'title':'Settings',
    'tab.account':'Account','acct.head':'Account & sync','acct.desc':'Registration, login and data sync (maps, snapshots, settings, Vault) across devices.',
    'tab.lang':'Language','tab.appearance':'Appearance','tab.ai':'AI','tab.install':'Installation',
    'tab.shortcuts':'Shortcuts',
    'sc.head':'Keyboard & mouse shortcuts','sc.desc':'The full list of shortcuts. Keys are shown as keys; the action depends on the mode (CodeMap / MindMap).',
    'sc.grp.nav':'CodeMap navigation','sc.grp.general':'General','sc.grp.mind':'MindMap',
    'sc.move':'Camera movement','sc.zoomIn':'Zoom in','sc.zoomOut':'Zoom out',
    'sc.fps':'Navigation mode (mouse-look, FPS)','sc.fpsHint':'Enable with G or the crosshair button; mouse = rotate and tilt; Esc or G = exit.',
    'sc.arrows':'Pan the view','sc.fit':'Fit to screen','sc.rotate':'Rotate left / right',
    'sc.resetRot':'Reset rotation','sc.toggle3d':'Toggle 3D / perspective','sc.isolate':'Focus on selected',
    'sc.impact':'Dependency impact view','sc.search':'Search','sc.escape':'Deselect / close','sc.del':'Delete node','sc.undo':'Undo / redo','sc.edit':'Edit node',
    'sc.altS':'Open / close this shortcuts cheatsheet',
    'sc.nodeNav':'Next node in that direction','sc.nodeNavHint':'the selection is announced to screen readers',
    'sc.nodeOpen':'Expand / collapse folder, show file','sc.nodeParent':'Parent folder / first child',
    'sc.mouse':'mouse','sc.dblclick':'double-click',
    'ai.head':'AI assistant (Mistral)','ai.desc':'Optional. With your own Mistral API key, the app can analyze the project STRUCTURE (folders, file counts and sizes, languages) and propose a logical grouping into modules/layers plus flag structural smells.',
    'ai.key':'Mistral API key (stored locally)','ai.model':'Model',
    'ai.keys':'API keys (cloud: Mistral, OpenAI, Anthropic Claude, Google Gemini, Groq, OpenRouter, DeepSeek, xAI, Together)',
    'ai.keysHint':'Paste a key — the provider is recognised from the key format and confirmed by a test (fetching its model list). Keys stay in this browser and go only to that provider\'s API. The app rotates through working keys and falls over to the next one on rate limits or errors.',
    'ai.keyAdd':'Add key','ai.keyTest':'Test','ai.keySave':'Save','ai.keyDelete':'Delete key','ai.keyDeleteConfirm':'Delete this key?',
    'ai.keySaved':'Key saved.','ai.keyDeleted':'Key deleted.','ai.keyEmpty':'Paste a key.','ai.keyExists':'This key is already on the list.',
    'ai.keyTesting':'Checking the key…','ai.keyOk':'works','ai.keyModels':'models: ','ai.keyUnknownProv':'provider not recognised from the format — click Test',
    'ai.keyDetected':'(detected from the key format — click Test to confirm)','ai.keyModel':'Model','ai.keyNone':'No keys yet. Add one below — or pick the local model or Ollama above (no key needed).',
    'ai.keyPh':'API key…','ai.keyShow':'Show / hide key','ai.keysCount':'Working keys: ',
    'ai.votes':'ChatBot answer ratings','ai.votesHint':'Total thumbs across all conversations — never resets.','ai.votesUp':'helpful','ai.votesDown':'unhelpful',
    'ai.provider':'AI provider','ai.providerHint':'"Local model" = a real, free LLM running 100% on your device (WebGPU). No key, no data leaves your machine — weights are downloaded once and kept in the browser cache.',
    'ai.provMistral':'API keys — cloud (Mistral, OpenAI, Claude, Gemini, Groq…)','ai.provLocal':'Local model (in-browser, free)',
    'ai.provOllama':'Ollama (native local server — blazing fast)',
    'ai.ollamaDesc':'The fastest local option: models run in your installed Ollama (ollama.com) — full machine power, zero load on the browser tab or its GPU. Requires the Ollama app running.',
    'ai.ollamaCheck':'Check / refresh models','ai.ollamaModel':'Ollama model','ai.ollamaOnline':'✓ Ollama online — models: ',
    'ai.localModel':'Local model','ai.localDl':'Download & start','ai.localDlHint':'The first start downloads the model weights (size next to the name). Subsequent starts are fast (browser cache). On integrated GPUs (Intel/AMD) prefer 0.5B–1B; bigger models need a dedicated GPU.',
    'ai.localReady':'✓ Model ready — the whole app (ChatBot, analysis, element questions) runs locally.',
    'ai.localLoading':'Downloading / starting…','ai.localNoGPU':'This browser has no WebGPU (Chrome/Edge 113+ required). Local models are unavailable — use the Mistral API.',
    'ai.localUnload':'Release from memory (RAM/VRAM)','ai.localDelete':'Delete downloaded weights from disk','ai.localDeleted':'Deleted model downloads: ','ai.localCached':'Model data downloaded in this browser: ',
    'ai.localCancel':'Cancel download / load',
    'ai.localAll':'All WebLLM engine models','ai.localAllHint':'The full chat-model list built into the WebLLM version in use (VRAM in MB). Picking one adds it to the list above.','ai.localAllShow':'Show all models','ai.localAllPick':'— pick a model —',
    'ai.rag':'Code index (RAG) — "📚 code" mode in ChatBot','ai.ragDesc':'In 📚 mode ChatBot answers from code snippets of the loaded project. Keyword search always works; an embedding model in Ollama (e.g. bge-m3 — multilingual, or nomic-embed-text) or 🌐 in the browser (WebLLM, needs WebGPU; downloaded once) adds semantic search. Vectors are computed on your machine and stored in the browser — on the next load only changed snippets are recomputed.',
    'ai.ragModel':'Embedding model','ai.ragNoModel':'No embedding model — pull bge-m3 or nomic-embed-text in Ollama, or use a browser with WebGPU (🌐 WebLLM models).','ai.ragWeb':'in the browser (WebLLM, English-first)','ai.ragBuild':'Build / refresh the semantic index','ai.ragCancel':'Cancel','ai.ragClear':'Delete vectors',
    'ai.ragAgent':'Agent with tools: in 📚 mode the Ollama model searches the code, reads files and checks dependencies before answering (read-only; models without tools answer as usual)',
    'ai.ragStat':'Snippets: {c} from {f} files · semantic index: {v}','ai.ragNoProject':'Load a project with file contents to build the index.','ai.ragYes':'ready ({m}, {d} dims)','ai.ragNo':'none (keyword search only)','ai.ragDone':'Semantic index ready: ',
    'ai.ollamaPull':'Pull a model into Ollama','ai.ollamaPullHint':'Name as in the ollama.com library (e.g. qwen2.5:3b). The download runs inside Ollama; progress below.','ai.ollamaPullBtn':'Pull','ai.ollamaPullDone':'Pulled: ','ai.ollamaPullCancel':'Cancel','ai.ollamaSuggest':'Suggestions: ',
    'ai.localList':'Downloaded models (manage)','ai.localNone':'No models downloaded yet.','ai.localRun':'Start (downloaded — no re-download)',
    'ai.localLoaded':'loaded','ai.localDelOne':'Delete','ai.localDelConfirm':'Delete the downloaded weights of "{n}" from this browser?',
    'ai.privacy':'Privacy: only the STRUCTURE is sent (paths, counts, sizes, languages) — never file contents. The key stays only in your browser.',
    'ai.analyze':'Analyze current structure','ai.working':'Analyzing structure…','ai.noProject':'Load a project first (CodeMap).','ai.empty':'No response.',
    'ai.autotune':'Auto-tune the view with AI on load','ai.autotuneHint':'After a project loads, AI chooses which Elements & Connections to show and the Figure params (node size, spacing, label size) so the map fits the project scale. Needs the key above; sends only the structure.',
    'ai.askHead':'Ask about the project','ai.askPlaceholder':'Ask about the project… e.g. where is the login logic?','ai.ask':'Ask AI','ai.asking':'Asking AI…','ai.askEmpty':'Type a question first.',
    'ai.layout':'✨ Let AI arrange the map','ai.layoutHint':'AI arranges the modules on its own — different every time, no preset layouts.','ai.layoutWorking':'AI is arranging the map…','ai.layoutDone':'AI arranged the map.',
    'tab.tutorial':'Tutorial','tab.spec':'Specification','tab.manual':'User manual','tab.about':'About',
    'lang.head':'Interface language','lang.desc':'Choose the application language. The whole interface is translated instantly and your choice is remembered.',
    'lang.pl':'Polski (Polish)','lang.en':'English',
    'app.head':'Appearance tuning','app.desc':'Full sliders for transparency, blur, colors and sizes live in the “Layers & filters” panel on the left. Here are quick shortcuts.',
    'app.theme':'Theme','app.theme.dark':'Dark','app.theme.light':'Light',
    'app.accent':'Accent color','app.open':'Open appearance panel','app.reset':'Restore default look',
    'app.reset.done':'Default look restored.',
    'install.head':'Installation & data','install.desc':'CodeMap is a PWA — you can install it on your desktop and use it offline. Your maps and settings are stored locally in the browser.',
    'install.install':'Install app','install.install.hint':'Add CodeMap as a standalone (offline) application.',
    'install.unavailable':'Install unavailable — the app is already installed or the browser did not offer a prompt. You can also use “Install” in the address bar.',
    'install.update':'Check for updates / reload','install.update.hint':'Fetches the latest version and refreshes the app.',
    'install.uninstall':'Clear offline cache','install.uninstall.hint':'Removes the service worker and cache. Maps and settings remain.',
    'install.uninstall.done':'Offline cache cleared. Refresh the page.',
    'install.acache':'Clear analysis cache','install.acache.hint':'File analysis results kept in the browser (OPFS) — reloading a project skips unchanged files. Only metrics, imports and symbol names.','install.acache.stat':'Now: {n} projects, {mb} MB.','install.acache.done':'Analysis cache cleared.',
    'install.wipe':'Delete all data','install.wipe.hint':'Permanently deletes snapshots, saved maps, mind maps, settings and language. Irreversible.',
    'install.wipe.confirm':'Really delete ALL data (snapshots, maps, settings)? This cannot be undone.',
    'install.wipe.done':'All application data deleted.',
    'tut.head':'Interactive tutorial','tut.desc':'An animated guide highlights each tool and button in turn and explains what it does. You can stop anytime with the Esc key.',
    'tut.start':'Start tutorial','tut.covers':'The tutorial shows: the logo, mode switch, Load menu, layout selector, search, Project menu, settings, side panels, filters, appearance, view tools, 3D with the mouse wheel, the compass (red needle), the neighborhood map/teleport, pinning the compass, the minimap, the details panel and the status bar.',
    'tut.startCode':'CodeMap tutorial','tut.startMind':'MindMap tutorial',
    'tut.coversMind':'The MindMap tutorial shows: the mode switch, the top bar (name + zoom), the board (double-click = new node), the tools rail (undo/redo, connect, auto-arrange, schemes & templates, fit), save & load, export, Markdown, the properties panel and the snapshot timeline.',
    'tut.shortcutsTitle':'Keyboard shortcuts',
    'tut.shortcuts':'<b>Ctrl + K</b> (on Windows also <b>Ctrl + ⊞ Win + K</b>) — <b>command palette</b> (quickly search and run any feature) · <b>Ctrl + V</b> — paste code · <b>F</b> — fit view · <b>Q / E</b> — rotate · <b>+ / −</b> — zoom · <b>I</b> — isolate selected · <b>Ctrl + Z / Ctrl + Y</b> — undo / redo (MindMap) · <b>Esc</b> — close / clear.',
    'tut.next':'Next','tut.prev':'Back','tut.skip':'Skip','tut.done':'Finish','tut.step':'Step',
    'about.head':'About','about.version':'Version','about.author':'Author','about.tech':'Technology',
    'about.tech.val':'Pure JavaScript (no frameworks, no build step), rendered on HTML5 Canvas, a PWA with a service worker. Works fully locally and offline.',
    'about.privacy':'Privacy','about.privacy.val':'All data stays in your browser. Files are never uploaded to any server (except when you explicitly fetch from GitHub/GitLab/Bitbucket).',
    'about.repo':'Author’s GitHub profile',
    // ---- tour steps ----
    'tour.brand.t':'CodeMap logo','tour.brand.b':'Click the logo to spin it (a playful touch, available every 10 seconds). It is also the app’s signature mark.',
    'tour.mode.t':'Mode switch','tour.mode.b':'Switch between <b>CodeMap</b> (code & dependency map) and <b>MindMap</b> (mind maps & diagrams). You can change mode anytime.',
    'tour.load.t':'Load menu','tour.load.b':'Load a project: a <b>folder from your device</b>, <b>individual files</b>, or a <b>GitHub/GitLab/Bitbucket repository</b>. You can also drag files onto the canvas or paste with Ctrl+V.',
    'tour.layout.t':'Layout selector','tour.layout.b':'Change how nodes are arranged — structural layouts (readable trees, packed circles), force-directed (dependency graph) and cosmic ones (nebula, galaxies).',
    'tour.search.t':'Search','tour.search.b':'Search files and paths. Matches are highlighted on the map; pick a result to jump straight to it.',
    'tour.project.t':'Project menu','tour.project.b':'Whole-project operations: save <b>snapshots</b> and their history, export the map to <b>.json</b> or an <b>image (PNG/SVG)</b>, detect <b>dependency cycles</b>, find <b>hotspots</b> and compare schemas.',
    'tour.settings.t':'Settings','tour.settings.b':'This gear opens settings — language, installation, this tutorial, and the full specification and user manual.',
    'tour.leftrail.t':'Side panel','tour.leftrail.b':'This handle collapses and expands the left panel with layers and filters. A matching handle on the right controls the details panel.',
    'tour.elements.t':'Elements & filters','tour.elements.b':'Toggle the visibility of folders, files and external dependencies — and of the connection types between them.',
    'tour.filetypes.t':'File types','tour.filetypes.b':'Each language/file type has its own color. You can hide selected types to focus the map on what matters.',
    'tour.complexity.t':'Complexity filter','tour.complexity.b':'Show only files above a threshold of the chosen metric (line count, complexity, function count, TODO markers, size). Great for finding “heavy” files.',
    'tour.appearance.t':'Appearance','tour.appearance.b':'Tune window transparency, glass blur, accent color, theme and background. The app is fully customizable.',
    'tour.map.t':'Map options','tour.map.b':'Toggle animations, flow particles, the background grid, curved connections and code preview on hover. You can also lock shapes here.',
    'tour.figures.t':'Shapes','tour.figures.b':'Adjust node size, distance between nodes and label size so the map stays readable for tiny and huge projects alike.',
    'tour.viewcontrols.t':'View tools','tour.viewcontrols.b':'Zoom in/out, fit to screen, rotate left/right and toggle pseudo-3D. The bar can be collapsed.',
    'tour.threed.t':'3D with the mouse wheel','tour.threed.b':'Press the <b>middle mouse button</b> and move <b>up / down</b> to smoothly and dynamically enter <b>3D</b> mode (perspective tilt) and back. The cube button on the toolbar does the same — it’s highlighted right now. (Rotate in 3D: middle or right mouse button.)',
    'tour.compass.t':'Compass — red needle','tour.compass.b':'Drag the <b>dial</b> to rotate the camera; the dial shows an <b>angle counter</b> (e.g. 0°). The <b>red needle</b> always points to the <b>centre of the main structure</b> on the map — so you always know the way “back to the project”, even when zoomed far out.',
    'tour.compasshood.t':'Neighborhood map (radar)','tour.compasshood.b':'<b>Double-clicking</b> the compass opens this <b>full neighborhood radar</b> — a miniature of every visible node. Scroll to zoom, and <b>double-click an item to teleport</b> straight to it on the map (there’s also a “Teleport to…” button). Great for jumping to a distant part of a large project.',
    'tour.compasspin.t':'Unpin & pin the compass','tour.compasspin.b':'The little <b>pin</b> button (top-left) <b>unpins</b> the compass; grab it by its <b>handle</b> (top) and move it <b>anywhere on screen</b>, then <b>pin</b> it back there with the same button. The other button collapses the compass.',
    'tour.minimap.t':'Minimap','tour.minimap.b':'An overview of the whole map with the current viewport marked. Helps navigate big projects; it can be collapsed.',
    'tour.details.t':'Details panel','tour.details.b':'After clicking an element you’ll see metrics, line composition, markers, imports, symbols (functions/classes) and a highlighted code preview here.',
    'tour.status.t':'Status bar','tour.status.b':'Project name, node and connection counts, the element under the cursor, the zoom level and a clock.',
    // ---- MindMap tour steps ----
    'tourmm.mode.t':'MindMap mode','tourmm.mode.b':"You're in <b>MindMap</b> mode — the mind-map and diagram editor. Use this switch to return to <b>CodeMap</b> anytime.",
    'tourmm.topbar.t':'Top bar','tourmm.topbar.b':'Name your mind map here and adjust the <b>zoom</b> (with +/− or the mouse wheel).',
    'tourmm.canvas.t':'The board','tourmm.canvas.b':'<b>Double-click</b> empty space to create a node, <b>double-click a node</b> to edit it, drag to pan. A quick-action <b>menu</b> surrounds the selected node (child, color, shape).',
    'tourmm.tools.t':'Tools rail','tourmm.tools.b':'Every mind-map tool in one place — the next steps cover the most useful ones.',
    'tourmm.undo.t':'Undo / redo','tourmm.undo.b':'Undo and redo changes (also with <b>Ctrl+Z</b> / <b>Ctrl+Y</b>).',
    'tourmm.connect.t':'Connecting nodes','tourmm.connect.b':'Turn on <b>connect mode</b> and click two nodes to link them with an edge.',
    'tourmm.arrange.t':'Auto-arrange','tourmm.arrange.b':'Automatically lays out the nodes (radially) — a quick tidy-up.',
    'tourmm.layout.t':'Schemes & templates','tourmm.layout.b':'Pick a <b>layout scheme</b>, line style and one of <b>22 diagram types</b> and 34 templates (timeline, flowchart, SWOT, kanban, code block and more).',
    'tourmm.fit.t':'Fit view','tourmm.fit.b':'Adjusts the zoom so the whole map fits on screen.',
    'tourmm.save.t':'Save & load','tourmm.save.b':'Save maps to device memory and load them later. Next to it: <b>export</b> to file, image (PNG/SVG) and import.',
    'tourmm.markdown.t':'Markdown','tourmm.markdown.b':'Import and export the map as a <b>Markdown outline</b> — easy exchange with your notes.',
    'tourmm.inspector.t':'Properties panel','tourmm.inspector.b':'With a node selected, tune its <b>text, color, shape, font</b> and links here. The handle beside it collapses the panel.',
    'tourmm.timeline.t':'Snapshot timeline','tourmm.timeline.b':'Saved snapshots line up on a <b>timeline</b> with an animated diff (added / changed / removed nodes).',
  }
};
