// ARCHITECTURE.md z mapy (cli/architecture.mjs): warstwy w kolejności dostawcy → konsumenci z ⚠ przy zależności
// „pod prąd", pakiety tylko przy ≥ 2, punkty wejścia, rdzeń, konwencja testów, reguły i cykle, determinizm.
import { test, describe, before, after } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { runAnalysis } from '../cli/analyze.mjs';
import { architectureMarkdown } from '../cli/architecture.mjs';

let dir;
const write = (rel, text) => { const p = path.join(dir, ...rel.split('/')); fs.mkdirSync(path.dirname(p), { recursive: true }); fs.writeFileSync(p, text); };
const md = async (lang) => { const r = await runAnalysis(dir, { git: false, coverage: false, modules: ['testgen'], lang }); return architectureMarkdown(r.CM, r.graph, r.report, { lang, version: '9.9.9' }); };

before(() => {
  dir = fs.mkdtempSync(path.join(os.tmpdir(), 'codemap-arch-'));
  write('package.json', '{ "name": "shop", "scripts": { "test": "node --test" } }');
  write('lib/core.js', 'export function total(xs) { let s = 0; for (const x of xs) { if (x > 0) s += x; } return s; }\n');
  write('lib/fmt.js', "import { total } from './core.js';\nexport const fmt = (xs) => String(total(xs));\n");
  write('app/main.js', "import { total } from '../lib/core.js';\nimport { fmt } from '../lib/fmt.js';\nimport { View } from './view.js';\nexport const run = () => new View(fmt([total([1])]));\n");
  write('app/view.js', "import { total } from '../lib/core.js';\nexport class View { constructor(t) { this.t = t + total([2]); } }\n");
  write('test/core.test.js', "import { total } from '../lib/core.js';\n");
  write('NOTES.txt', 'notes\n');   // typ „Tekst" → „Text" po angielsku
  write('.codemap.rules.json', '{ "layers": [ { "name": "lib", "match": ["lib/**"] }, { "name": "app", "match": ["app/**"] } ], "forbid": [ { "from": "lib", "to": "app" } ] }');
});
after(() => { fs.rmSync(dir, { recursive: true, force: true }); });

describe('ARCHITECTURE.md', () => {
  test('warstwy: lib (dostawca) nad app; punkty wejścia, rdzeń, testy z konwencją, reguły bez naruszeń; bez tabeli pakietów', async () => {
    const m = await md('en');
    assert.match(m, /^# Architecture — codemap-arch-\w+\n\n> Generated by CodeMap 9\.9\.9/);
    const rows = m.split('\n').filter((l) => /^\| \d+ \| /.test(l));
    assert.ok(rows.findIndex((l) => l.includes('| lib |')) < rows.findIndex((l) => l.includes('| app |')), rows.join('\n'));
    assert.match(m, /\| app \| 2 \| lib 3 \|/);
    assert.ok(!m.includes('## Packages'));
    assert.match(m, /## Entry points\n\n.*\n\n- `app\/main\.js` — imports 3/);
    assert.match(m, /## Core modules\n\n.*\n\n- `lib\/core\.js` — imported by 4/);
    assert.match(m, /Convention: tests in a mirrored tree `test\/` \(`\*\.test\.js`\), node:test\./);
    assert.match(m, /`\.codemap\.rules\.json`: layers 2, forbidden dependencies 1, violations 0\./);
    assert.match(m, /languages: JavaScript 5, JSON 2, Text 1/);
    assert.match(m, /No import cycles between files\./);
    assert.equal(await md('en'), m, 'deterministyczne');
  });
  test('zależność „pod prąd" (lib → app) = ⚠ cykl i naruszenie reguły; po polsku', async () => {
    write('lib/hook.js', "import { View } from '../app/view.js';\nexport const hook = () => new View(1);\n");
    try {
      const m = await md('pl');
      assert.match(m, /^# Architektura — /);
      assert.match(m, /⚠ cykl/);
      assert.match(m, /naruszeń 1\./);
      assert.match(m, /języki: JavaScript 6, JSON 2, Tekst 1/);
    } finally { fs.rmSync(path.join(dir, 'lib', 'hook.js')); }
  });
});
