// ARCHITECTURE.md z mapy (cli/architecture.mjs): warstwy w kolejności dostawcy → konsumenci z ⚠ przy zależności
// „pod prąd", pakiety tylko przy ≥ 2, punkty wejścia, rdzeń, konwencja testów, reguły i cykle, determinizm.
import { test, describe, before, after } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { runAnalysis } from '../cli/analyze.mjs';
import { architectureMarkdown } from '../cli/architecture.mjs';
import { writeTree, LAYER_RULES, ROOT } from './harness.mjs';
import { spawnSync } from 'node:child_process';
import { createServer } from '../cli/mcp.mjs';

const CLI = path.join(ROOT, 'cli', 'codemap.mjs');

let dir;
const write = (rel, text) => writeTree(dir, rel, text);
const md = async (lang) => { const r = await runAnalysis(dir, { git: false, coverage: false, modules: ['testgen'], lang }); return architectureMarkdown(r.CM, r.graph, r.report, { lang, version: '9.9.9' }); };

before(() => {
  dir = fs.mkdtempSync(path.join(os.tmpdir(), 'codemap-arch-'));
  write('package.json', '{ "name": "shop", "scripts": { "test": "node --test" } }');
  write('lib/core.js', 'export function total(xs) { let s = 0; for (const x of xs) { if (x > 0) s += x; } return s; }\n');
  write('lib/fmt.js', "import { total } from './core.js';\nexport const fmt = (xs) => String(total(xs));\n");
  write('app/main.js', "import { total } from '../lib/core.js';\nimport { fmt } from '../lib/fmt.js';\nimport { View } from './view.js';\nexport const run = () => new View(fmt([total([1])]));\n");
  write('app/view.js', "import { total } from '../lib/core.js';\nexport class View { constructor(t) { this.t = t + total([2]); } }\n");
  write('test/core.test.js', "import { total } from '../lib/core.js';\n");
  write('NOTES.txt', 'notes\n');   // typ „Tekst" → „Text" po angielsku
  write('.codemap.rules.json', LAYER_RULES);
});
after(() => { fs.rmSync(dir, { recursive: true, force: true }); });

describe('ARCHITECTURE.md', () => {
  test('warstwy: lib (dostawca) nad app; punkty wejścia, rdzeń, testy z konwencją, reguły bez naruszeń; bez tabeli pakietów', async () => {
    const m = await md('en');
    assert.match(m, /^# Architecture — codemap-arch-\w+\n\n> Generated by CodeMap 9\.9\.9/);
    const rows = m.split('\n').filter((l) => /^\| \d+ \| /.test(l));
    assert.ok(rows.findIndex((l) => l.includes('| lib |')) < rows.findIndex((l) => l.includes('| app |')), rows.join('\n'));
    assert.match(m, /\| app \| 2 \| lib 3 \|/);
    assert.ok(!m.includes('## Packages'));
    assert.match(m, /## Entry points\n\n.*\n\n- `app\/main\.js` — imports 3/);
    assert.match(m, /## Core modules\n\n.*\n\n- `lib\/core\.js` — imported by 4/);
    assert.match(m, /Convention: tests in a mirrored tree `test\/` \(`\*\.test\.js`\), node:test\./);
    assert.match(m, /`\.codemap\.rules\.json`: layers 2, forbidden dependencies 1, violations 0\./);
    assert.match(m, /languages: JavaScript 5, JSON 2, Text 1/);
    assert.match(m, /No import cycles between files\./);
    assert.equal(await md('en'), m, 'deterministyczne');
  });
  test('codemap rules: propozycja z warstw folderów na stdout, podsumowanie na stderr, --out; MCP propose_rules', async () => {
    const r = spawnSync(process.execPath, [CLI, 'rules', dir, '--folders', '--lang', 'en'], { encoding: 'utf8' });
    assert.equal(r.status, 0, r.stderr);
    const j = JSON.parse(r.stdout);
    assert.ok(j.layers.some((l) => l.name === 'lib' && l.match === 'lib/**') && j.layers.some((l) => l.name === 'app'));
    const lib = j.forbid.find((f) => f.from === 'lib');
    assert.ok(lib && [].concat(lib.to).includes('app'), JSON.stringify(j.forbid));
    assert.match(r.stderr, /Proposed rules \(folders\): layers \d+, forbidden \d+, exceptions to fix \(upstream dependencies\) 0/);
    const out = path.join(dir, 'proposal.json');
    assert.equal(spawnSync(process.execPath, [CLI, 'rules', dir, '--folders', '--out', out, '-q', '--lang', 'en'], { encoding: 'utf8' }).status, 0);
    assert.deepEqual(JSON.parse(fs.readFileSync(out, 'utf8')), j); fs.rmSync(out);
    const srv = createServer({ dir, lang: 'en', git: false, log: () => {} });
    const res = (await srv.handle({ jsonrpc: '2.0', id: 1, method: 'tools/call', params: { name: 'propose_rules', arguments: { mode: 'folders' } } })).result;
    assert.match(res.content[0].text, /^folders: \d+ layers, 0 upstream dependencies to fix[\s\S]*"from": "lib"/);
  });
  test('zależność „pod prąd" (lib → app) = ⚠ cykl i naruszenie reguły; po polsku', async () => {
    write('lib/hook.js', "import { View } from '../app/view.js';\nexport const hook = () => new View(1);\n");
    try {
      const m = await md('pl');
      assert.match(m, /^# Architektura — /);
      assert.match(m, /⚠ cykl/);
      assert.match(m, /naruszeń 1\./);
      assert.match(m, /języki: JavaScript 6, JSON 2, Tekst 1/);
    } finally { fs.rmSync(path.join(dir, 'lib', 'hook.js')); }
  });
});
