// Reguły Inspect na małych grafach: precyzja reguł poprawiona w fazie 9 (hub, ryzyko innerHTML, pliki generowane,
// cykle bez dokumentacji, duplikaty jako ciągłe bloki) — każdy przypadek to fałszywy alarm z analizy samego CodeMap.
import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { loadCM, host } from './harness.mjs';
import { CLI_MODULES } from '../cli/runtime.mjs';

const CM = loadCM(CLI_MODULES);
const { Graph } = CM.Graph;
const F = (path, content) => ({ path, content, size: content.length, mtime: 1 });
const run = async (files) => host(await CM.Inspect.run(new Graph().build(files, { name: 't', source: 'test' })));
const rule = (res, r) => res.findings.find((f) => f.rule === r);
const paths = (res, r) => { const f = rule(res, r); return f ? f.items.map((i) => i.path).sort() : []; };
const lines = (n, fn) => Array.from({ length: n }, (_, i) => fn(i)).join('\n') + '\n';

describe('Inspect: god = hub w obie strony', () => {
  test('plik importowany przez 12 i importujący 12 → god; wejście (fan-in 0) → fan-out, nie god', async () => {
    const files = [F('src/hub.js', lines(12, (i) => `import b${i} from './b${i}.js';`))];
    for (let i = 0; i < 12; i++) files.push(F(`src/a${i}.js`, `import h from './hub.js';\nexport const a${i} = h;\n`), F(`src/b${i}.js`, `export default ${i};\n`));
    assert.deepEqual(paths(await run(files), 'god'), ['src/hub.js']);
    const entry = [F('index.html', lines(22, (i) => `<script src="js/m${i}.js"></script>`))];
    for (let i = 0; i < 22; i++) entry.push(F(`js/m${i}.js`, `window.m${i} = ${i};\n`));
    const res = await run(entry);
    assert.deepEqual(paths(res, 'god'), []);
    assert.deepEqual(paths(res, 'fanout'), ['index.html']);
  });
  test('pomocnik testów importowany przez 22 testy nie jest hubem', async () => {
    const files = [F('test/harness.mjs', "import { x } from '../src/x.js';\nimport { y } from '../src/y.js';\nimport { z } from '../src/z.js';\nexport const h = x + y + z;\n"),
      F('src/x.js', 'export const x = 1;\n'), F('src/y.js', 'export const y = 1;\n'), F('src/z.js', 'export const z = 1;\n')];
    for (let i = 0; i < 22; i++) files.push(F(`test/t${i}.test.mjs`, "import { h } from './harness.mjs';\nexport default h;\n"));
    assert.deepEqual(paths(await run(files), 'god'), []);
  });
});

describe('Inspect: ryzyko, pliki generowane, cykle', () => {
  test('innerHTML = "" (czyszczenie) i porównanie nie są ryzykiem; wstawienie treści jest', async () => {
    const res = await run([
      F('src/clear.js', "box.innerHTML = '';\nlist.innerHTML=\"\";\nif (el.innerHTML == '') go();\n"),
      F('src/set.js', "box.innerHTML = '';\nbox.innerHTML = html;\n"),
    ]);
    const r = rule(res, 'risky');
    assert.deepEqual(paths(res, 'risky'), ['src/set.js']);
    assert.match(r.items[0].detail, /1/);
  });
  test('plik blokady i plik z nagłówkiem „DO NOT EDIT" nie są „ogromne"; zwykły kod tak', async () => {
    const res = await run([
      F('package-lock.json', lines(900, (i) => `"k${i}": ${i},`)),
      F('api.pb.go', '// Code generated by protoc-gen-go. DO NOT EDIT.\n' + lines(900, (i) => `var v${i} = ${i}`)),
      F('src/big.js', lines(900, (i) => `export const v${i} = ${i};`)),
    ]);
    assert.deepEqual(paths(res, 'huge'), ['src/big.js']);
  });
  test('linki między dokumentami (README ↔ tłumaczenie) nie tworzą cyklu; import a ↔ b tak', async () => {
    const res = await run([
      F('README.md', '# X\n[Polski](README.pl.md)\n'), F('README.pl.md', '# X\n[English](README.md)\n'),
      F('src/a.js', "import { b } from './b.js';\nexport const a = 1;\n"), F('src/b.js', "import { a } from './a.js';\nexport const b = 2;\n"),
    ]);
    const c = rule(res, 'cycles');
    assert.equal(c.count, 1);
    assert.ok(['src/a.js', 'src/b.js'].includes(c.items[0].path));
  });
  test('cykl między pakietami monorepo → „pkgcycle" (wysoka) na folderze pakietu; bez cyklu pakietów — brak', async () => {
    const pk = [F('p1/package.json', '{ "name": "p1" }'), F('p2/package.json', '{ "name": "p2" }')];
    const res = await run([...pk, F('p1/a.js', "import { b } from '../p2/b.js';\nexport const a = 1;\n"), F('p2/b.js', "import { a } from '../p1/a.js';\nexport const b = 2;\n")]);
    const p = rule(res, 'pkgcycle');
    assert.equal(p.sev, 'high'); assert.equal(p.count, 1);
    assert.equal(p.items[0].path, 'p1'); assert.deepEqual(p.items[0].related, ['p2']);
    assert.match(p.items[0].detail, /^p1 → p2 → p1/);
    const ok = await run([...pk, F('p1/a.js', "import { b } from '../p2/b.js';\n"), F('p2/b.js', 'export const b = 2;\n')]);
    assert.equal(rule(ok, 'pkgcycle'), undefined);
  });
});

describe('Inspect: puste catch tylko w kodzie', () => {
  test('catch {} w napisie, szablonie i komentarzu się nie liczy; w kodzie — tak', async () => {
    const res = await run([
      F('src/str.js', "const a = 'try { x() } catch (e) {}';\nconst b = `catch {}`;\n// catch (e) {}\n/* catch {} */\nexport default a + b;\n"),
      F('src/real.js', 'try { go(); } catch (e) {}\ntry { go(); } catch {}\nexport const r = 1;\n'),
      // uzasadnienie w środku (blokowe albo liniowe) = świadome zignorowanie, nie puste catch (regresja z 1.5.0)
      F('src/why.js', 'try { go(); } catch (e) { /* tryb prywatny: brak localStorage */ }\ntry { go(); } catch {\n  // już przerwane\n}\nexport const w = 1;\n'),
    ]);
    const r = rule(res, 'emptycatch');
    assert.deepEqual(r.items.map((i) => [i.path, i.detail]), [['src/real.js', 'w ok. 2 miejscach']]);
  });
});

describe('Inspect: ukryte sprzężenie zmian', () => {
  test('para kodu zmieniana razem bez importu → zgłoszona; z importem, z testem albo rzadka → nie', async () => {
    const files = [
      F('src/a.js', 'export const a = 1;\n'), F('src/b.js', 'export const b = window.A;\n'),       // razem, bez importu
      F('src/c.js', "import { d } from './d.js';\nexport const c = d;\n"), F('src/d.js', 'export const d = 1;\n'),   // razem, z importem
      F('test/a.test.js', "import { a } from '../src/a.js';\n"),                                    // test ↔ kod
      F('src/e.js', 'export const e = 1;\n'), F('src/f.js', 'export const f = 1;\n'),                // razem tylko 3×
    ];
    const g = new Graph().build(files, { name: 't', source: 'test' });
    const T0 = Date.UTC(2026, 0, 1), cs = [];
    const commit = (paths, i) => cs.push({ sha: 'c' + cs.length, parents: [], merge: false, author: { name: 'Ala Kowalska', email: 'a@x.pl' },
      authorTime: T0 + i * 864e5, time: T0 + i * 864e5, message: 'm', files: paths.map((p) => ({ path: p, status: 'M' })) });
    for (let i = 0; i < 6; i++) { commit(['src/a.js', 'src/b.js', 'test/a.test.js'], i); commit(['src/c.js', 'src/d.js'], i); }
    for (let i = 0; i < 3; i++) commit(['src/e.js', 'src/f.js'], 10 + i);
    for (let i = 0; i < 3; i++) commit(['src/e.js'], 20 + i);
    CM.GitCore.applyToGraph(g, CM.GitCore.analyze(cs.reverse(), files.map((f) => f.path)), { source: 'test' });
    const res = host(await CM.Inspect.run(g));
    const h = rule(res, 'hiddencoupling');
    assert.equal(h.count, 1);
    assert.deepEqual([h.items[0].path, ...h.items[0].related].sort(), ['src/a.js', 'src/b.js']);
    assert.match(h.items[0].detail, /wspólne commity: 6, stopień: 100 %/);
  });
});

describe('Inspect: duplikaty', () => {
  const BLOCK = lines(14, (i) => `  const part${i} = normalize(input.slice(${i} * width, (${i} + 1) * width), options.mode, ${i});`);
  test('ciągły wspólny blok w dwóch plikach kodu → para z tokenami; to samo w README i tłumaczeniu → nic', async () => {
    const res = await run([
      F('src/one.js', 'export function one(input, width, options) {\n' + BLOCK + '  return part0;\n}\n' + lines(8, (i) => `export const oneOnly${i} = ${i * 3};`)),
      F('src/two.js', 'function two(input, width, options) {\n' + BLOCK + '  return part1;\n}\n' + lines(8, (i) => `const twoOnly${i} = "${i}";`)),
      F('docs/a.md', '# A\n' + BLOCK), F('docs/a.pl.md', '# A (PL)\n' + BLOCK),
    ]);
    const d = rule(res, 'dupcode');
    assert.equal(d.count, 1);
    assert.deepEqual([d.items[0].path, ...d.items[0].related].sort(), ['src/one.js', 'src/two.js']);
    assert.match(d.items[0].detail, /tokeny: \d+, bloki: 1/);
  });
});
