// ARCHITECTURE.md z mapy (faza 15) — `codemap analyze --architecture <plik>` i narzędzie MCP `architecture`:
// warstwy (kolejność z macierzy zależności: dostawcy → konsumenci; zależność „pod prąd" = cykl), pakiety monorepo,
// punkty wejścia, moduły rdzenia (najczęściej importowane), hotspoty z właścicielami, własność warstw, testy i ich
// konwencja, reguły architektury, cykle, ukryte sprzężenia. Deterministyczne (bez daty) — diff w repozytorium pokazuje
// zmiany struktury, a nie godzinę wygenerowania.

const T = {
  en: { title: 'Architecture', gen: 'Generated by CodeMap {v} from the code and git history — regenerate with `codemap analyze . --architecture ARCHITECTURE.md`; do not edit by hand.',
    overview: 'Overview', files: 'files', lines: 'lines', score: 'health score', findings: 'findings', langs: 'languages',
    layers: 'Layers', layersPk: 'Packages', order: 'Order from the dependency matrix: providers first, consumers below — a unit depends only on units above it, except where marked ⚠ (an upstream dependency, i.e. a cycle).',
    unit: 'unit', dependsOn: 'depends on (imports)', nothing: '—', cycle: '⚠ cycle',
    entries: 'Entry points', entriesNote: 'Code files nothing imports, which import others (start reading here).', imports: 'imports',
    core: 'Core modules', coreNote: 'Most imported code files — changes here ripple the furthest.', importedBy: 'imported by', cx: 'complexity',
    hot: 'Hotspots', hotNote: 'Changed often and complex (git history) — where bugs and the cost of change accumulate.', hotNoGit: 'Large and complex files (no git history).', changes: 'changes', owner: 'owner',
    own: 'Ownership', bus: 'bus factor', tests: 'Tests', testsLine: '{t} of {c} code files have tests ({p} %).', conv: 'Convention: {k}, {f}.',
    convKinds: { sibling: 'tests next to the code', __tests__: 'tests in `__tests__/` next to the code', mirror: 'tests in a mirrored tree `{r}/`', flat: 'tests in `{r}/`', inline: 'test module in the same file', java: 'tests in `src/test/…`' },
    rules: 'Rules and cycles', rulesFile: '`.codemap.rules.json`: layers {l}, forbidden dependencies {f}, violations {v}.', noRules: 'No `.codemap.rules.json` — `codemap rules` proposes one from the layers above (DSM window: Propose rules).',
    cycles: 'Import cycles: {n}{big}.', noCycles: 'No import cycles between files.', pkgCycles: 'Package cycles: {l}.',
    hidden: 'Hidden coupling', hiddenNote: 'Code files changed together without an import between them (git history).' },
  pl: { title: 'Architektura', gen: 'Wygenerowane przez CodeMap {v} z kodu i historii git — odśwież: `codemap analyze . --architecture ARCHITECTURE.md`; nie edytuj ręcznie.',
    overview: 'Przegląd', files: 'plików', lines: 'linii', score: 'wynik zdrowia', findings: 'znaleziska', langs: 'języki',
    layers: 'Warstwy', layersPk: 'Pakiety', order: 'Kolejność z macierzy zależności: dostawcy u góry, konsumenci niżej — jednostka zależy tylko od jednostek nad nią, poza oznaczonymi ⚠ (zależność „pod prąd", czyli cykl).',
    unit: 'jednostka', dependsOn: 'zależy od (importy)', nothing: '—', cycle: '⚠ cykl',
    entries: 'Punkty wejścia', entriesNote: 'Pliki kodu, których nikt nie importuje, a które importują inne (od nich zacznij czytanie).', imports: 'importuje',
    core: 'Moduły rdzenia', coreNote: 'Najczęściej importowane pliki kodu — zmiana tutaj sięga najdalej.', importedBy: 'importowany przez', cx: 'złożoność',
    hot: 'Hotspoty', hotNote: 'Często zmieniane i złożone (historia git) — tu kumulują się błędy i koszt zmian.', hotNoGit: 'Duże i złożone pliki (bez historii git).', changes: 'zmian', owner: 'właściciel',
    own: 'Własność', bus: 'bus factor', tests: 'Testy', testsLine: 'Pliki kodu z testami: {t} z {c} ({p} %).', conv: 'Konwencja: {k}, {f}.',
    convKinds: { sibling: 'testy obok kodu', __tests__: 'testy w `__tests__/` obok kodu', mirror: 'testy w lustrzanym drzewie `{r}/`', flat: 'testy w `{r}/`', inline: 'moduł testów w tym samym pliku', java: 'testy w `src/test/…`' },
    rules: 'Reguły i cykle', rulesFile: '`.codemap.rules.json`: warstw {l}, zakazanych zależności {f}, naruszeń {v}.', noRules: 'Brak `.codemap.rules.json` — `codemap rules` zaproponuje go z warstw powyżej (okno DSM: Zaproponuj reguły).',
    cycles: 'Cykle importów: {n}{big}.', noCycles: 'Brak cykli importów między plikami.', pkgCycles: 'Cykle pakietów: {l}.',
    hidden: 'Ukryte sprzężenia', hiddenNote: 'Pliki kodu zmieniane razem bez importu między nimi (historia git).' },
};
const fill = (s, o) => s.replace(/\{(\w+)\}/g, (m, k) => (o[k] != null ? o[k] : m));
const esc = (s) => String(s).replace(/\|/g, '\\|');

/** Markdown architektury; CM — moduły z runAnalysis (DSM, TestMap, GitCore, TestGen jeśli załadowany). */
export function architectureMarkdown(CM, graph, report, opts = {}) {
  const L = T[opts.lang === 'pl' ? 'pl' : 'en'], out = [];
  const files = [...graph.nodes.values()].filter((n) => n.type === 'file' && n.path);
  const isCode = (n) => (CM.TestMap ? CM.TestMap.isCodeFile(n.path) : /\.(m?[jt]sx?|py|go|rs|java|kt|cs|rb|php|swift|c|cc|cpp|h|hpp)$/.test(n.path));
  const gi = graph.gitInfo, au = (gi && gi.authors) || [];
  const byLang = new Map(); for (const x of (report.stats.languages || [])) byLang.set(x.name, (byLang.get(x.name) || 0) + x.files);

  out.push(`# ${L.title} — ${report.project.name}`, '', `> ${fill(L.gen, { v: opts.version || '' })}`, '');
  out.push(`## ${L.overview}`, '',
    `- ${report.stats.files} ${L.files}, ${report.stats.lines} ${L.lines}; ${L.langs}: ${[...byLang].sort((a, b) => b[1] - a[1] || (a[0] < b[0] ? -1 : 1)).slice(0, 6).map(([k, v]) => `${CM.languages.label(k, L === T.pl ? 'pl' : 'en')} ${v}`).join(', ')}`,
    `- ${L.score}: ${report.score}/100; ${L.findings}: ${report.totals.findings} (high ${report.totals.high}, med ${report.totals.med}, low ${report.totals.low})`, '');

  // warstwy z macierzy zależności: zawsze foldery pierwszego poziomu, a przy ≥ 2 pakietach także pakiety
  const table = (m, title, note) => {
    out.push(`## ${title}`, '', note, '', `| # | ${L.unit} | ${L.files} | ${L.dependsOn} |`, '|--:|---|--:|---|');
    const nm = (u) => (u.id === CM.DSM.OUTSIDE ? '(root)' : u.name);
    m.units.forEach((u, i) => {
      const deps = m.cells[i].map((n, j) => [n, j]).filter(([n, j]) => n && j !== i).sort((a, b) => b[0] - a[0] || a[1] - b[1])
        .map(([n, j]) => `${nm(m.units[j])} ${n}${j > i ? ' ' + L.cycle : ''}`);
      out.push(`| ${i + 1} | ${esc(nm(u) + (m.mode === 'packages' && u.dir ? ` (\`${u.dir}\`)` : ''))} | ${u.files} | ${esc(deps.join(', ') || L.nothing)} |`);
    });
    out.push('');
  };
  const m = CM.DSM.matrix(graph, { mode: 'folders', depth: 1 });
  table(m, L.layers, L.order);
  if ((graph.packages || []).length >= 2) table(CM.DSM.matrix(graph, { mode: 'packages' }), L.layersPk, '');

  // punkty wejścia i moduły rdzenia
  const code = files.filter((n) => isCode(n) && !n.isTest);
  const inN = (n) => (n.importsIn || []).length, outN = (n) => (n.importsOut || []).length;
  const entries = code.filter((n) => inN(n) === 0 && outN(n) > 0).sort((a, b) => outN(b) - outN(a) || (a.path < b.path ? -1 : 1)).slice(0, 10);
  if (entries.length) out.push(`## ${L.entries}`, '', L.entriesNote, '', ...entries.map((n) => `- \`${n.path}\` — ${L.imports} ${outN(n)}`), '');
  const core = code.filter((n) => inN(n) > 1).sort((a, b) => inN(b) - inN(a) || (a.path < b.path ? -1 : 1)).slice(0, 10);
  if (core.length) out.push(`## ${L.core}`, '', L.coreNote, '', ...core.map((n) => `- \`${n.path}\` — ${L.importedBy} ${inN(n)}, ${L.cx} ${(n.metrics && n.metrics.complexity) || 0}`), '');

  // hotspoty
  const hs = (report.hotspots || []).slice(0, 8);
  if (hs.length) {
    const idx = new Map(files.map((n) => [n.path, n]));
    out.push(`## ${L.hot}`, '', gi ? L.hotNote : L.hotNoGit, '');
    for (const h of hs) { const n = idx.get(h.path), o = n && n.git && n.git.own != null && au[n.git.own] ? au[n.git.own].name : null;
      out.push(`- \`${h.path}\` — ${L.cx} ${h.complexity}${h.changes != null ? `, ${h.changes} ${L.changes}` : ''}${o ? `, ${L.owner} ${o}` : ''}`); }
    out.push('');
  }

  // własność warstw (git)
  if (gi && CM.GitCore) {
    const rows = [];
    for (const u of m.units) { if (u.id === CM.DSM.OUTSIDE) continue; const f = graph.nodes.get(u.dir); const fs = f && CM.GitCore.folderStats(graph, f);
      if (!fs || !fs.authors.length) continue; const tot = fs.authors.reduce((s, x) => s + x[1], 0) || 1;
      rows.push(`- \`${u.dir}/\` — ${fs.authors.slice(0, 3).map((x) => `${(au[x[0]] || {}).name || '?'} ${Math.round(x[1] / tot * 100)} %`).join(', ')}; ${L.bus} ${fs.busFactor.value}`); }
    if (rows.length) out.push(`## ${L.own}`, '', ...rows, '');
  }

  // testy i konwencja
  const ti = graph.testInfo;
  if (ti && ti.code) {
    out.push(`## ${L.tests}`, '', fill(L.testsLine, { t: ti.tested, c: ti.code, p: ti.pct }));
    if (CM.TestGen && ti.tests) {
      const sample = code.find((n) => n.testedBy && n.testedBy.length) || code[0];
      if (sample) {
        const conv = CM.TestGen.convention(graph, sample), kind = conv.kind.split(':')[0], root = conv.kind.split(':')[1] || '';
        const ext = sample.path.slice(sample.path.lastIndexOf('.') + 1);
        const fw = /^(js|mjs|cjs|jsx|ts|tsx|mts|cts)$/.test(ext) ? CM.TestGen.jsFramework(graph, sample) : ext === 'py' ? CM.TestGen.pyFramework(graph) : '';
        out.push(fill(L.conv, { k: fill(L.convKinds[kind] || kind, { r: root }) + (conv.suffix ? ` (\`${conv.suffix === 'test_' ? 'test_*.py' : '*' + conv.suffix}\`)` : ''), f: fw === 'node' ? 'node:test' : fw || '—' }));
      }
    }
    out.push('');
  }

  // reguły i cykle
  out.push(`## ${L.rules}`, '');
  const rulesNode = CM.Rules && CM.Rules.findRulesNode ? CM.Rules.findRulesNode(graph) : graph.nodes.get('.codemap.rules.json'), viol = (report.findings.find((f) => f.rule === 'archviolation') || {}).count || 0;
  if (rulesNode && CM.Rules && rulesNode.preview) { try { const r = CM.Rules.parse(rulesNode.preview); out.push(fill(L.rulesFile, { l: (r.layers || []).length, f: (r.forbid || []).length, v: viol })); } catch { out.push(L.noRules); } }
  else out.push(L.noRules);
  const cyc = (graph.importCycles().components || []);
  out.push(cyc.length ? fill(L.cycles, { n: cyc.length, big: ` (${Math.max(...cyc.map((c) => c.length))} max)` }) : L.noCycles);
  const pc = (graph.packages || []).length >= 2 ? CM.DSM.packageCycles(graph) : [];
  if (pc.length) out.push(fill(L.pkgCycles, { l: pc.map((c) => c.map((u) => u.name).join(' ↔ ')).join('; ') }));
  out.push('');

  // ukryte sprzężenia (reguła hiddencoupling)
  const hc = report.findings.find((f) => f.rule === 'hiddencoupling');
  if (hc && hc.items.length) out.push(`## ${L.hidden}`, '', L.hiddenNote, '', ...hc.items.slice(0, 8).map((it) => (it.related && it.related.length   // para pełnymi ścieżkami, opis bez „razem z <nazwa>"
    ? `- \`${it.path}\` ↔ \`${it.related[0]}\` — ${it.detail.split(' — ').slice(1).join(' — ')}`
    : `- \`${it.path}\` — ${it.detail}`)), '');
  return out.join('\n').replace(/\n{3,}/g, '\n\n');
}
